const DBKEY=window.INDICA_CONFIG.storageKey;
function getData(){let d=localStorage.getItem(DBKEY);return d?JSON.parse(d):null}
function saveData(d){localStorage.setItem(DBKEY,JSON.stringify(d))}
function uid(p="id"){return p+"_"+Math.random().toString(36).slice(2,9)+Date.now().toString(36).slice(-4)}
function fmt(s){return new Date(s).toLocaleDateString("pt-BR")}
function toast(msg){let t=document.getElementById("toast");if(!t){t=document.createElement("div");t.id="toast";t.className="toast";document.body.appendChild(t)}t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2500)}
function modal(html){document.getElementById("adminModalContent").innerHTML=html;document.getElementById("adminModal").classList.add("open");document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>document.getElementById("adminModal").classList.remove("open"))}
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
function init(){
 const nav=document.querySelectorAll(".nav-item");nav.forEach(n=>n.onclick=()=>{nav.forEach(x=>x.classList.remove("active"));n.classList.add("active");show(n.dataset.view)});
 show("dashboard");
}
function show(v){document.querySelectorAll(".admin-view").forEach(x=>x.classList.remove("active"));document.getElementById("view-"+v).classList.add("active");document.getElementById("viewTitle").textContent={dashboard:"Dashboard",indications:"Indicações",tickets:"Tickets",prizes:"Prêmios",campaign:"Campanha",reports:"Relatórios"}[v];({dashboard:renderDash,indications:renderIndications,tickets:renderTickets,prizes:renderPrizes,campaign:renderCampaign,reports:renderReports}[v])()}
function renderDash(){
 const d=getData(), confirmed=d.referrals.filter(r=>r.status==="confirmed").length, available=d.tickets.filter(t=>t.status==="available").length;
 document.getElementById("view-dashboard").innerHTML=`<div class="admin-cards"><div class="a-card"><small>Alunos</small><strong>${d.students.length}</strong></div><div class="a-card"><small>Indicações</small><strong>${d.referrals.length}</strong></div><div class="a-card"><small>Matrículas confirmadas</small><strong>${confirmed}</strong></div><div class="a-card"><small>Tickets disponíveis</small><strong>${available}</strong></div></div><div class="admin-panel"><div class="panel-head"><h2>Últimas indicações</h2><button class="a-btn primary" onclick="show('indications')">Ver todas</button></div>${recentRefs(d)}</div>`;
}
function recentRefs(d){if(!d.referrals.length)return '<div class="empty">Ainda não existem indicações.</div>';return `<div class="table-wrap"><table class="admin-table"><thead><tr><th>Indicado</th><th>Quem indicou</th><th>Data</th><th>Status</th></tr></thead><tbody>${d.referrals.slice(-8).reverse().map(r=>{let s=d.students.find(x=>x.id===r.studentId);return `<tr><td><b>${esc(r.name)}</b><br><small>${esc(r.phone)}</small></td><td>${esc(s?.name||"—")}</td><td>${fmt(r.createdAt)}</td><td>${badge(r.status)}</td></tr>`}).join("")}</tbody></table></div>`}
function badge(s){return `<span class="status ${s==="confirmed"?"confirmed":s==="cancelled"?"cancelled":"pending"}">${s==="confirmed"?"CONFIRMADA":s==="cancelled"?"CANCELADA":"AGUARDANDO"}</span>`}
function renderIndications(){
 const d=getData();
 document.getElementById("view-indications").innerHTML=`<div class="admin-panel"><div class="filters"><input id="searchRef" placeholder="Buscar indicado, telefone ou indicador..." oninput="renderRefTable()"><select id="statusRef" onchange="renderRefTable()"><option value="">Todos os status</option><option value="pending">Aguardando</option><option value="confirmed">Confirmadas</option><option value="cancelled">Canceladas</option></select></div><div id="refTable"></div></div>`;
 renderRefTable();
}
function renderRefTable(){
 const d=getData(),q=(document.getElementById("searchRef")?.value||"").toLowerCase(),st=document.getElementById("statusRef")?.value||"";
 let rows=d.referrals.filter(r=>{let s=d.students.find(x=>x.id===r.studentId);return (!st||r.status===st)&&(!q||`${r.name} ${r.phone} ${s?.name||""} ${r.email}`.toLowerCase().includes(q))});
 document.getElementById("refTable").innerHTML=`<div class="table-wrap"><table class="admin-table"><thead><tr><th>Lead</th><th>Indicador</th><th>Data</th><th>Elegível</th><th>Status</th><th>Ação</th></tr></thead><tbody>${rows.length?rows.slice().reverse().map(r=>{let s=d.students.find(x=>x.id===r.studentId),ready=Date.now()>=new Date(r.eligibleAt).getTime();return `<tr><td><b>${esc(r.name)}</b><br><small>${esc(r.phone)} · ${esc(r.email||"sem e-mail")}</small></td><td>${esc(s?.name||"—")}</td><td>${fmt(r.createdAt)}</td><td>${fmt(r.eligibleAt)}</td><td>${badge(r.status)}</td><td>${r.status==="pending"?`<button class="a-btn primary" onclick="confirmRef('${r.id}',${ready})">Confirmar matrícula</button>`:"—"}</td></tr>`}).join(""):'<tr><td colspan="6" class="empty">Nenhuma indicação encontrada.</td></tr>'}</tbody></table></div>`;
}
function confirmRef(id,ready){
 if(!ready&&!confirm("Esta indicação ainda não completou os 7 dias. Deseja fazer uma liberação excepcional?"))return;
 const d=getData(),r=d.referrals.find(x=>x.id===id);if(!r||r.status!=="pending")return;r.status="confirmed";r.confirmedAt=new Date().toISOString();r.confirmedBy="admin";
 const code="IND-"+Math.random().toString(36).substring(2,6).toUpperCase()+"-"+Math.random().toString(36).substring(2,6).toUpperCase();
 d.tickets.push({id:uid("tic"),studentId:r.studentId,referralId:r.id,code,status:"available",createdAt:new Date().toISOString()});saveData(d);toast("Matrícula confirmada e ticket gerado!");renderIndications();
}
function renderTickets(){
 const d=getData();document.getElementById("view-tickets").innerHTML=`<div class="admin-panel"><div class="panel-head"><h2>Tickets emitidos</h2><span class="pill">${d.tickets.length} total</span></div><div class="table-wrap"><table class="admin-table"><thead><tr><th>Ticket</th><th>Aluno</th><th>Emissão</th><th>Status</th><th>Prêmio</th></tr></thead><tbody>${d.tickets.length?d.tickets.slice().reverse().map(t=>{let s=d.students.find(x=>x.id===t.studentId),p=d.prizes.find(x=>x.id===t.prizeId);return `<tr><td><code>${t.code}</code></td><td>${esc(s?.name||"—")}</td><td>${fmt(t.createdAt)}</td><td>${t.status==="available"?'<span class="status confirmed">DISPONÍVEL</span>':'<span class="status pending">UTILIZADO</span>'}</td><td>${p?esc(p.name):"—"}</td></tr>`}).join(""):'<tr><td colspan="5" class="empty">Nenhum ticket emitido.</td></tr>'}</tbody></table></div></div>`;
}
function renderPrizes(){
 const d=getData();document.getElementById("view-prizes").innerHTML=`<div class="admin-panel"><div class="panel-head"><h2>Prêmios da campanha</h2><button class="a-btn primary" onclick="newPrize()">+ Novo prêmio</button></div>${d.prizes.map(p=>`<div class="prize-admin"><div><span style="font-size:28px">${p.icon}</span> <b>${esc(p.name)}</b><br><small>${esc(p.desc)} · estoque: ${p.stock}</small></div><div><button class="a-btn" onclick="editPrize('${p.id}')">Editar</button> <button class="a-btn ${p.active?'danger':''}" onclick="togglePrize('${p.id}')">${p.active?'Desativar':'Ativar'}</button></div></div>`).join("")}</div>`;
}
function newPrize(p=null){modal(`<span class="eyebrow">PRÊMIO</span><h2>${p?"Editar":"Cadastrar"} prêmio</h2><form id="prizeForm"><div class="field"><label>Nome</label><input id="pn" value="${esc(p?.name||"")}" required></div><div class="field"><label>Descrição</label><textarea id="pd">${esc(p?.desc||"")}</textarea></div><div class="field"><label>Emoji / ícone</label><input id="pi" value="${esc(p?.icon||"🎁")}"></div><div class="field"><label>Estoque</label><input id="ps" type="number" min="0" value="${p?.stock??1}"></div><button class="btn btn-primary">Salvar prêmio</button></form>`);document.getElementById("prizeForm").onsubmit=e=>{e.preventDefault();let d=getData();if(p){Object.assign(d.prizes.find(x=>x.id===p.id),{name:pn.value,desc:pd.value,icon:pi.value,stock:+ps.value})}else d.prizes.push({id:uid("p"),name:pn.value,desc:pd.value,icon:pi.value,stock:+ps.value,active:true});saveData(d);document.getElementById("adminModal").classList.remove("open");renderPrizes();toast("Prêmio salvo.")}}
function editPrize(id){let d=getData();newPrize(d.prizes.find(p=>p.id===id))}
function togglePrize(id){let d=getData(),p=d.prizes.find(x=>x.id===id);p.active=!p.active;saveData(d);renderPrizes()}
function renderCampaign(){
 const d=getData(),c=d.campaign;document.getElementById("view-campaign").innerHTML=`<div class="campaign-grid"><div class="admin-panel"><div class="panel-head"><h2>Identidade da campanha</h2></div><form id="campaignForm"><div class="field"><label>Nome da campanha</label><input id="cn" value="${esc(c.name)}"></div><div class="field"><label>Selo / badge</label><input id="cb" value="${esc(c.badge)}"></div><div class="field"><label>Título principal</label><input id="ct" value="${esc(c.title)}"></div><div class="field"><label>Subtítulo</label><textarea id="cs">${esc(c.subtitle)}</textarea></div><div class="field"><label>Texto da marca</label><input id="cl" value="${esc(c.logoText)}"></div><div class="field"><label>Cores</label><div class="color-row"><input id="cp" type="color" value="${c.primary}"><input id="c2" type="color" value="${c.secondary}"></div></div><button class="btn btn-primary">Salvar alterações</button></form></div><div class="admin-panel"><div class="panel-head"><h2>Pré-visualização</h2></div><div class="preview" id="campaignPreview" style="background:linear-gradient(135deg,${c.primary},${c.secondary})"><span id="pvb">${esc(c.badge)}</span><h2 id="pvt">${esc(c.title)}</h2><p id="pvs">${esc(c.subtitle)}</p><button class="btn btn-light" style="width:max-content">🎟️ Quero participar</button></div></div></div>`;
 ["cn","cb","ct","cs","cl","cp","c2"].forEach(id=>document.getElementById(id).addEventListener("input",previewCampaign));
 document.getElementById("campaignForm").onsubmit=e=>{e.preventDefault();let d=getData();Object.assign(d.campaign,{name:cn.value,badge:cb.value,title:ct.value,subtitle:cs.value,logoText:cl.value,primary:cp.value,secondary:c2.value});saveData(d);toast("Campanha atualizada.");previewCampaign()}
}
function previewCampaign(){let c={name:cn.value,badge:cb.value,title:ct.value,subtitle:cs.value,logoText:cl.value,primary:cp.value,secondary:c2.value};pvb.textContent=c.badge;pvt.textContent=c.title;pvs.textContent=c.subtitle;campaignPreview.style.background=`linear-gradient(135deg,${c.primary},${c.secondary})`}
function renderReports(){
 const d=getData();document.getElementById("view-reports").innerHTML=`<div class="admin-panel"><div class="panel-head"><div><h2>Exportar dados</h2><p>Escolha um período e baixe os leads ou o relatório de indicações.</p></div></div><div class="filters"><input type="date" id="fromDate"><input type="date" id="toDate"><button class="a-btn primary" onclick="exportLeads()">📊 Leads Excel</button><button class="a-btn" onclick="exportRanking()">📊 Ranking Excel</button><button class="a-btn" onclick="exportLeadsPDF()">📄 Leads PDF</button></div><div class="a-card"><b>O que sai no relatório de leads?</b><p>Nome, WhatsApp, telefone, e-mail, quem indicou, data e status da indicação.</p><b>Ranking</b><p>Aluno indicador, quantidade de indicações, matrículas confirmadas e tickets gerados.</p></div></div>`;
}
function rangeFilter(date){const f=document.getElementById("fromDate")?.value,t=document.getElementById("toDate")?.value;let x=new Date(date);if(f&&x<new Date(f+"T00:00:00"))return false;if(t&&x>new Date(t+"T23:59:59"))return false;return true}
function getLeadRows(){let d=getData();return d.referrals.filter(r=>rangeFilter(r.createdAt)).map(r=>{let s=d.students.find(x=>x.id===r.studentId);return [r.name,r.phone,r.phone,r.email||"",s?.name||"",fmt(r.createdAt),r.status==="confirmed"?"Confirmada":r.status==="cancelled"?"Cancelada":"Aguardando"]})}
function csv(rows,headers){let body=[headers,...rows].map(r=>r.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(";")).join("\n");return "\ufeff"+body}
function download(content,name,type){let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function exportLeads(){download(csv(getLeadRows(),["Nome","WhatsApp","Telefone","E-mail","Quem indicou","Data","Status"]),"indica-mais-leads.csv","text/csv;charset=utf-8");toast("Arquivo de leads exportado.")}
function exportRanking(){let d=getData(),m={};d.referrals.forEach(r=>{if(!rangeFilter(r.createdAt))return;let s=d.students.find(x=>x.id===r.studentId);if(!s)return;m[s.id]??={nome:s.name,indicacoes:0,matriculas:0,tickets:0};m[s.id].indicacoes++;if(r.status==="confirmed")m[s.id].matriculas++});d.tickets.forEach(t=>{if(m[t.studentId])m[t.studentId].tickets++});let rows=Object.values(m).sort((a,b)=>b.indicacoes-a.indicacoes).map(x=>[x.nome,x.indicacoes,x.matriculas,x.tickets, x.indicacoes?((x.matriculas/x.indicacoes)*100).toFixed(1)+"%":"0%"]);download(csv(rows,["Aluno","Indicações","Matrículas confirmadas","Tickets","Conversão"]),"indica-mais-ranking.csv","text/csv;charset=utf-8");toast("Ranking exportado.")}
function exportLeadsPDF(){let rows=getLeadRows(),w=window.open("","_blank");w.document.write(`<html><head><title>Indica+ - Leads</title><style>body{font-family:Arial;padding:30px}h1{color:#6d28d9}table{border-collapse:collapse;width:100%;font-size:11px}th,td{border:1px solid #ddd;padding:7px;text-align:left}</style></head><body><h1>Indica+ | Leads</h1><p>Relatório gerado em ${new Date().toLocaleString("pt-BR")}</p><table><tr><th>Nome</th><th>WhatsApp</th><th>Telefone</th><th>E-mail</th><th>Quem indicou</th><th>Data</th><th>Status</th></tr>${rows.map(r=>"<tr>"+r.map(c=>`<td>${esc(c)}</td>`).join("")+"</tr>").join("")}</table><script>window.print()</script></body></html>`);w.document.close()}
init();
